In [4]:

import pandas as pd

# Load dataset
df = pd.read_csv("/boot/task1_raw_dataset.csv")
df

  Customer Name   Age  Gender Country      Join Date   Salary
0         Pooja  23.0  Female   India     12-01-2023  25000.0
1         Rahul  35.0    male   india     2023/02/15  40000.0
2         Anita   NaN  FEMALE   INDIA  15 March 2023  32000.0
3         Rahul  35.0    male   india     2023/02/15  40000.0
4        Vikram  29.0   Male      USA            NaN      NaN
5           NaN  41.0  Female      UK     07-07-2022  50000.0
6         Sneha  30.0     NaN  India      2023-08-01  28000.0

In [2]:
#  Check basic info
print(df.info())
print(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer Name  6 non-null      object
 1   Age            6 non-null      float64
 2   Gender         6 non-null      object
 3   Country        7 non-null      object
 4   Join Date      6 non-null      object
 5   Salary         6 non-null      float64
dtypes: float64(2), object(4)
memory usage: 468.0+ bytes
None
  Customer Name   Age  Gender Country      Join Date   Salary
0         Pooja  23.0  Female   India     12-01-2023  25000.0
1         Rahul  35.0    male   india     2023/02/15  40000.0
2         Anita   NaN  FEMALE   INDIA  15 March 2023  32000.0
3         Rahul  35.0    male   india     2023/02/15  40000.0
4        Vikram  29.0   Male      USA            NaN      NaN

In [5]:
import pandas as pd
import numpy as np

In [6]:
# Load dataset
df = pd.read_csv("/boot/netflix_dataset_task1.csv")
df

,show_id,type,title,director,country,date_added,release_year,rating,duration
0,s1,Movie,The Great Escape,John Sturges,United States,"September 9, 2019",1963,PG,172 min
1,s2,TV Show,Friends,NaN,United states,2018-01-01,1994,TV-14,10 Seasons
2,s3,Movie,Money Heist,Alex Pina,Spain,15 March 2020,2017,TV-MA,2 Seasons
3,s4,movie,The Great Escape,John Sturges,United States,"September 9, 2019",1963,PG,172 min
4,s5,TV show,Breaking Bad,NaN,NaN,2017/05/05,2008,NaN,5 Seasons
5,s6,Movie,Inception,Christopher Nolan,USA,2019-07-16,2010,PG-13,148 min
6,s7,TV Show,Stranger Things,Duffer Brothers,United States,July 15 2016,2016,TV-14,4 Seasons
7,s8,movie,Inception,Christopher Nolan,USA,2019-07-16,2010,PG-13,148 min
8,s9,TV Show,The Crown,NaN,UK,NaN,2016,TV-MA,5 Seasons
9,s10,Movie,Interstellar,Christopher Nolan,United States,2014/11/07,2014,PG-13,169 min

In [8]:
# Check Missing Values
print(df.isnull().sum())

show_id         0
type            0
title           0
director        3
country         1
date_added      1
release_year    0
rating          1
duration        0
dtype: int64

In [10]:
# Remove Duplicates
df = df.drop_duplicates();df

,show_id,type,title,director,country,date_added,release_year,rating,duration
0,s1,Movie,The Great Escape,John Sturges,United States,"September 9, 2019",1963,PG,172 min
1,s2,TV Show,Friends,NaN,United states,2018-01-01,1994,TV-14,10 Seasons
2,s3,Movie,Money Heist,Alex Pina,Spain,15 March 2020,2017,TV-MA,2 Seasons
3,s4,movie,The Great Escape,John Sturges,United States,"September 9, 2019",1963,PG,172 min
4,s5,TV show,Breaking Bad,NaN,NaN,2017/05/05,2008,NaN,5 Seasons
5,s6,Movie,Inception,Christopher Nolan,USA,2019-07-16,2010,PG-13,148 min
6,s7,TV Show,Stranger Things,Duffer Brothers,United States,July 15 2016,2016,TV-14,4 Seasons
7,s8,movie,Inception,Christopher Nolan,USA,2019-07-16,2010,PG-13,148 min
8,s9,TV Show,The Crown,NaN,UK,NaN,2016,TV-MA,5 Seasons
9,s10,Movie,Interstellar,Christopher Nolan,United States,2014/11/07,2014,PG-13,169 min

In [11]:
# Handle Missing Values
df["director"] = df["director"].fillna("Not Mentioned")
df["country"] = df["country"].fillna("Unknown")
df["rating"] = df["rating"].fillna("Not Rated")

In [12]:
# Standardize Text Columns
df["type"] = df["type"].str.title()
df["country"] = df["country"].str.title()

In [13]:
# Replace USA with United States
df["country"] = df["country"].replace("Usa", "United States")

In [14]:
# Convert Date Format
df["date_added"] = pd.to_datetime(df["date_added"], errors="coerce")

In [15]:
# Rename Columns
df.columns = df.columns.str.lower().str.replace(" ", "_")

In [16]:
# Save Cleaned Dataset
df.to_csv("netflix_cleaned_dataset.csv", index=False)
print("Data Cleaning Completed Successfully!")

Data Cleaning Completed Successfully!

In [17]:
print(df.head())

  show_id     type             title       director        country date_added  \
0      s1    Movie  The Great Escape   John Sturges  United States 2019-09-09
1      s2  Tv Show           Friends  Not Mentioned  United States        NaT
2      s3    Movie       Money Heist      Alex Pina          Spain        NaT
3      s4    Movie  The Great Escape   John Sturges  United States 2019-09-09
4      s5  Tv Show      Breaking Bad  Not Mentioned        Unknown        NaT

   release_year     rating    duration
0          1963         PG     172 min
1          1994      TV-14  10 Seasons
2          2017      TV-MA   2 Seasons
3          1963         PG     172 min
4          2008  Not Rated   5 Seasons